jobs:
  - job: jmeter
    pool:
      vmImage: ubuntu-latest
    displayName: Run JMeter tests
    steps:
      - task: Bash@3
        displayName: Execute JMeter tests
        inputs:
          targetType: filePath
          filePath: 'jmeter/test.sh'
          arguments: '$PWD consulta_datos_sensibles.jmx'
          workingDirectory: jmeter
          failOnStderr: false
      - task: PublishPipelineArtifact@1
        displayName: Publish JMeter Report
        inputs:
          targetPath: jmeter/report
          artifact: jmeter